#!/usr/bin/env node
// Changelog sync. Two hand-written sources, everything else is derived:
//   /CHANGELOG.md             public (beta testers): product only, no Vorath content
//   /docs/kairos/CHANGELOG.md private Vorath log (owner-only, server-only in the app)
//
//   node scripts/changelog-sync.mjs sync               regenerate changelog.ts, version.ts, changelog-private.ts
//   node scripts/changelog-sync.mjs check              exit 1 on drift, a Vorath leak, or a bad private import
//   node scripts/changelog-sync.mjs draft [--since R]  route conventional commits into public/private drafts

import { execFileSync } from 'node:child_process'
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..')

export const PATHS = {
  publicMd: 'CHANGELOG.md',
  privateMd: 'docs/kairos/CHANGELOG.md',
  changelogTs: 'apps/web/src/lib/changelog.ts',
  versionTs: 'apps/web/src/lib/version.ts',
  privateTs: 'apps/web/src/lib/changelog-private.ts',
  privateAction: 'apps/web/src/lib/actions/changelog-private.ts',
  kairosVersionTs: 'apps/web/src/lib/kairos/version.ts',
  src: 'apps/web/src',
}

// Anything matching this in the public log is Vorath content and fails `check`.
export const PRIVATE_TERMS = /\b(Vorath|Kairos|Dominions?|aether|Telegram|thinking jobs?|Hangar|AI DONE|second brain|memories)\b/i

// Ordinary product phrases the pattern would wrongly catch, matched case-insensitively against the
// whole line. Empty on purpose: the public log needs none today. Add an entry only with a reason.
export const PUBLIC_ALLOWLIST = []

// Commit scopes that always route to the private log. `capture` and `git-stats` feed Vorath's
// memory (session capture, nightly git digests), so they go private too.
export const PRIVATE_SCOPES = new Set([
  'kairos', 'vorath', 'dominion', 'dominions', 'aether', 'telegram', 'brain', 'hangar', 'eval', 'capture', 'git-stats',
])

const SCOPE_AREAS = {
  board: 'BOARD', gantt: 'GANTT', canvas: 'CANVAS', realm: 'REALM', realms: 'REALM', auth: 'AUTH', mcp: 'MCP',
  api: 'API', db: 'DATA', data: 'DATA', infra: 'INFRA', ci: 'INFRA', build: 'INFRA', deploy: 'INFRA',
  mobile: 'INFRA', docs: 'DOCS', ui: 'UI', sidebar: 'UI', theme: 'UI',
}

export const normalise = (s) => s.replace(/\r\n/g, '\n')

export function topVersion(md) {
  const m = md.match(/^## \[([^\]]+)\]/m)
  return m ? m[1] : null
}

export function escapeTemplate(s) {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

const GENERATED = (source) =>
  `// GENERATED by apps/web/scripts/changelog-sync.mjs from ${source}. Do not edit by hand:\n` +
  `// edit the markdown, then run \`npm run changelog:sync --workspace=apps/web\`.\n`

export function renderChangelogTs(publicMd) {
  return `${GENERATED('/CHANGELOG.md')}\nexport const CHANGELOG_MD = \`${escapeTemplate(normalise(publicMd))}\`\n`
}

export function renderVersionTs(version) {
  return `${GENERATED('/CHANGELOG.md')}// In-app version shown in the Changelog modal header. package.json "version" is intentionally unused.\n\nexport const APP_VERSION = '${version}'\n`
}

export function renderPrivateTs(privateMd) {
  const md = normalise(privateMd)
  return (
    `${GENERATED('/docs/kairos/CHANGELOG.md')}// Owner-only. Import it ONLY from lib/actions/changelog-private.ts; \`check\` enforces that,\n` +
    `// and 'server-only' fails any client bundle that pulls it in.\nimport 'server-only'\n\n` +
    `export const PRIVATE_CHANGELOG_VERSION = '${topVersion(md) ?? ''}'\n\n` +
    `export const PRIVATE_CHANGELOG_MD = \`${escapeTemplate(md)}\`\n`
  )
}

export function findPrivateTerms(text, allow = PUBLIC_ALLOWLIST) {
  const hits = []
  normalise(text).split('\n').forEach((line, i) => {
    const m = line.match(PRIVATE_TERMS)
    if (!m) return
    if (allow.some((phrase) => line.toLowerCase().includes(phrase.toLowerCase()))) return
    hits.push({ line: i + 1, term: m[0], text: line.trim().slice(0, 120) })
  })
  return hits
}

const IMPORT_RE = /(?:from\s+|import\s*\(\s*|import\s+|require\s*\(\s*)['"]([^'"]+)['"]/g

/** files: [{ path (repo-relative, forward slashes), content }]. Returns paths that import the private module. */
export function findPrivateImporters(files) {
  const target = PATHS.privateTs.replace(/\.ts$/, '')
  return files
    .filter((f) => f.path !== PATHS.privateAction && f.path !== PATHS.privateTs)
    .filter((f) =>
      [...f.content.matchAll(IMPORT_RE)].some(([, spec]) => {
        if (spec === '@/lib/changelog-private') return true
        if (!spec.startsWith('.')) return false
        const abs = join(dirname(f.path), spec).replace(/\\/g, '/').replace(/\.tsx?$/, '')
        return abs === target
      }),
    )
    .map((f) => f.path)
}

export function parseCommit(subject) {
  const m = subject.match(/^(\w+)(?:\(([^)]*)\))?(!)?:\s*(.+)$/)
  if (!m) return { type: null, scopes: [], breaking: false, description: subject.trim() }
  return {
    type: m[1].toLowerCase(),
    scopes: (m[2] ?? '').split(/[,/\s]+/).map((s) => s.trim().toLowerCase()).filter(Boolean),
    breaking: !!m[3],
    description: m[4].trim(),
  }
}

export function routeCommit(subject) {
  const c = parseCommit(subject)
  if (c.scopes.some((s) => PRIVATE_SCOPES.has(s))) return 'private'
  return PRIVATE_TERMS.test(subject) ? 'private' : 'public'
}

const SECTION_OF = (type) => (type === 'feat' ? 'Added' : type === 'fix' ? 'Fixed' : 'Changed')

function renderSide(commits, withAreas) {
  if (!commits.length) return '_Nothing to draft._\n'
  const groups = new Map()
  const areas = new Set()
  for (const { hash, subject } of commits) {
    const c = parseCommit(subject)
    const key = SECTION_OF(c.type)
    if (!groups.has(key)) groups.set(key, [])
    groups.get(key).push(`- ${c.description}${c.breaking ? ' **(breaking)**' : ''} (${hash})`)
    for (const s of c.scopes) if (SCOPE_AREAS[s]) areas.add(SCOPE_AREAS[s])
  }
  const out = []
  if (withAreas && areas.size) out.push(`> Areas touched: ${[...areas].map((a) => `\`${a}\``).join(' ')}`, '> Theme: <one line>', '')
  for (const key of ['Added', 'Changed', 'Fixed']) {
    if (!groups.has(key)) continue
    out.push(`### ${key}`, ...groups.get(key), '')
  }
  return out.join('\n')
}

/** commits: [{ hash, subject }] newest first. Merge commits should already be excluded. */
export function renderDraft(commits) {
  const pub = commits.filter((c) => routeCommit(c.subject) === 'public')
  const priv = commits.filter((c) => routeCommit(c.subject) === 'private')
  return { public: renderSide(pub, true), private: renderSide(priv, false), counts: { public: pub.length, private: priv.length } }
}

/** read(relPath) -> string|null. Returns the files `sync` would write. */
export function expectedFiles(read) {
  const publicMd = read(PATHS.publicMd)
  const privateMd = read(PATHS.privateMd)
  if (publicMd == null) throw new Error(`${PATHS.publicMd} not found`)
  if (privateMd == null) throw new Error(`${PATHS.privateMd} not found`)
  const version = topVersion(publicMd)
  if (!version) throw new Error(`${PATHS.publicMd} has no "## [x.y.z]" heading`)
  return [
    { path: PATHS.changelogTs, content: renderChangelogTs(publicMd) },
    { path: PATHS.versionTs, content: renderVersionTs(version) },
    { path: PATHS.privateTs, content: renderPrivateTs(privateMd) },
  ]
}

/** Pure check. read(relPath) -> string|null; sources: [{ path, content }] under apps/web/src. */
export function runCheck(read, sources) {
  const errors = []
  for (const f of expectedFiles(read)) {
    const current = read(f.path)
    if (current == null || normalise(current) !== f.content) errors.push(`${f.path} is out of date with its markdown (run changelog:sync)`)
  }
  for (const p of [PATHS.publicMd, PATHS.changelogTs]) {
    for (const hit of findPrivateTerms(read(p) ?? '')) errors.push(`${p}:${hit.line} mentions "${hit.term}" (private): ${hit.text}`)
  }
  const kairos = (read(PATHS.kairosVersionTs) ?? '').match(/KAIROS_VERSION\s*=\s*['"]([^'"]+)['"]/)?.[1]
  const privTop = topVersion(read(PATHS.privateMd) ?? '')
  if (kairos !== privTop) errors.push(`KAIROS_VERSION (${kairos ?? 'missing'}) does not match the private log's top version (${privTop ?? 'missing'})`)
  for (const p of findPrivateImporters(sources)) errors.push(`${p} imports the private changelog module; only ${PATHS.privateAction} may`)
  return errors
}

// ------------------------------------------------------------------ IO

const readRel = (rel) => {
  const abs = join(ROOT, rel)
  return existsSync(abs) ? readFileSync(abs, 'utf8') : null
}

function listSources(dir = join(ROOT, PATHS.src)) {
  const out = []
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const abs = join(dir, e.name)
    if (e.isDirectory()) out.push(...listSources(abs))
    else if (/\.(ts|tsx|js|jsx|mjs)$/.test(e.name)) {
      out.push({ path: relative(ROOT, abs).replace(/\\/g, '/'), content: readFileSync(abs, 'utf8') })
    }
  }
  return out
}

function git(args) {
  return execFileSync('git', args, { cwd: ROOT, encoding: 'utf8' })
}

function cmdSync() {
  let changed = 0
  for (const f of expectedFiles(readRel)) {
    const current = readRel(f.path)
    if (current != null && normalise(current) === f.content) continue
    writeFileSync(join(ROOT, f.path), f.content)
    changed++
    console.log(`wrote ${f.path}`)
  }
  console.log(changed ? `changelog:sync — ${changed} file(s) updated` : 'changelog:sync — already in sync')
  return 0
}

function cmdCheck() {
  const errors = runCheck(readRel, listSources())
  if (errors.length) {
    console.error(`changelog:check — ${errors.length} problem(s):`)
    for (const e of errors) console.error(`  ✗ ${e}`)
    return 1
  }
  const pub = topVersion(readRel(PATHS.publicMd))
  const priv = topVersion(readRel(PATHS.privateMd))
  console.log(`changelog:check — ok (public ${pub}, private ${priv}; no private terms in the public log; private module imported only by the server action)`)
  return 0
}

function cmdDraft(argv) {
  const i = argv.indexOf('--since')
  const since = i >= 0 ? argv[i + 1] : git(['log', '-1', '--format=%H', '--', PATHS.publicMd]).trim()
  if (!since) throw new Error('no --since ref and CHANGELOG.md has no history')
  const log = git(['log', `${since}..HEAD`, '--no-merges', '--format=%h%x09%s']).trim()
  const commits = log ? log.split('\n').map((l) => { const [hash, ...rest] = l.split('\t'); return { hash, subject: rest.join('\t') } }) : []
  const d = renderDraft(commits)
  console.log(`# Draft since ${since.slice(0, 12)} — ${d.counts.public} public, ${d.counts.private} private\n`)
  console.log(`## PUBLIC → /CHANGELOG.md (curate, then changelog:sync)\n\n${d.public}`)
  console.log(`## PRIVATE → /docs/kairos/CHANGELOG.md (owner-only)\n\n${d.private}`)
  return 0
}

export function main(argv) {
  const [cmd, ...rest] = argv
  if (cmd === 'sync') return cmdSync()
  if (cmd === 'check') return cmdCheck()
  if (cmd === 'draft') return cmdDraft(rest)
  console.error('usage: changelog-sync.mjs sync | check | draft [--since <ref>]')
  return 2
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exit(main(process.argv.slice(2)))
}
