export interface McpToolCategory {
  name: string
  tools: string[]
}

export const TOOL_CATEGORIES: McpToolCategory[] = [
  {
    name: 'Projects',
    tools: [
      'list_projects',
      'get_project',
      'create_project',
      'update_project',
      'set_project_favorite',
      'set_project_kairos_feed',
      'delete_project',
      'project_summary',
    ],
  },
  {
    name: 'Columns',
    tools: ['list_columns', 'create_column', 'update_column', 'delete_column', 'reorder_columns'],
  },
  {
    name: 'Tasks',
    tools: ['list_tasks', 'create_task', 'update_task', 'delete_task', 'get_task_detail'],
  },
  {
    name: 'Gantt',
    tools: [
      'list_gantt_tasks',
      'create_gantt_task',
      'update_gantt_task',
      'delete_gantt_task',
      'batch_create_gantt_tasks',
      'list_rows',
      'create_row',
      'update_row',
      'delete_row',
      'reorder_rows',
      'list_gantt_views',
      'create_gantt_view',
      'update_gantt_view',
      'delete_gantt_view',
    ],
  },
  {
    name: 'Dependencies',
    tools: ['list_dependencies', 'add_dependency', 'remove_dependency'],
  },
  {
    name: 'Labels',
    tools: [
      'list_labels',
      'create_label',
      'delete_label',
      'add_label_to_task',
      'remove_label_from_task',
      'set_task_labels',
    ],
  },
  {
    name: 'Checklist',
    tools: ['create_checklist_item', 'update_checklist_item', 'delete_checklist_item'],
  },
  {
    name: 'Comments',
    tools: ['list_comments', 'add_comment', 'update_comment', 'delete_comment'],
  },
  {
    name: 'Realms',
    tools: [
      'list_realms',
      'create_realm',
      'update_realm',
      'delete_realm',
      'list_realm_members',
      'invite_realm_member',
      'list_pending_realm_invites',
      'cancel_realm_invite',
      'resend_realm_invite',
      'remove_realm_member',
      'update_realm_member_role',
      'list_realm_projects',
      'add_project_to_realm',
      'remove_project_from_realm',
    ],
  },
  {
    name: 'Virtual members',
    tools: ['list_virtual_members', 'create_virtual_member', 'update_virtual_member', 'delete_virtual_member'],
  },
  {
    name: 'Hangar — sessions & repos',
    tools: [
      'spawn_session',
      'list_sessions',
      'get_session',
      'list_session_events',
      'kill_session',
      'claim_session',
      'register_hangar_repo',
      'list_hangar_repos',
      'update_hangar_repo',
      'delete_hangar_repo',
    ],
  },
  {
    name: 'Batch & Analytics',
    tools: [
      'batch_create_tasks',
      'batch_create_checklist_items',
      'batch_update_checklist_items',
      'batch_add_dependencies',
      'setup_board',
      'get_velocity_stats',
    ],
  },
  {
    name: 'Vorath — memory & brain',
    tools: [
      'create_memory',
      'update_memory',
      'search_memories',
      'link_memory',
      'prepare_context',
      'list_memories_needing_summary',
      'get_memory_with_neighbours',
      'get_belief_trail',
      'accept_proposal',
      'kairos_reflect',
      'list_memory_ops',
      'revert_memory_op',
    ],
  },
  {
    name: 'Vorath — beliefs, constitution & thinking jobs',
    tools: [
      'list_beliefs',
      'get_mind_comparison',
      'get_constitution',
      'propose_constitution_amendment',
      'claim_thinking_job',
      'submit_thinking_job',
      'list_thinking_jobs',
    ],
  },
  {
    name: 'Vorath — Dominions & recipes',
    tools: [
      'create_dominion',
      'list_dominions',
      'get_dominion',
      'update_dominion',
      'inspect_dominion',
      'get_dominion_focus',
      'list_objectives',
      'create_objective',
      'update_objective',
      'archive_objective',
      'delete_dominion',
      'list_dominion_repos',
      'add_dominion_repo',
      'remove_dominion_repo',
      'assign_project_dominion',
      'bulk_assign_projects_to_dominion',
      'get_trace_history',
    ],
  },
  {
    name: 'Vorath — Ask, Dialogue & Aether',
    tools: [
      'run_kairos_ask',
      'get_pending_kairos_ask',
      'list_open_kairos_asks',
      'answer_kairos_ask',
      'dismiss_kairos_ask',
      'kairos_voice_note',
      'get_kairos_paid_backup',
      'set_kairos_paid_backup',
      'list_kairos_promises',
      'get_kairos_today',
      'list_kairos_predictions',
      'list_kairos_agenda',
      'get_kairos_stage',
      'get_kairos_surprise',
      'get_kairos_idea_taste',
      'get_kairos_idea_atlas',
      'get_kairos_gate',
      'get_kairos_rapport',
      'get_kairos_trust',
      'get_kairos_life_chapters',
      'get_kairos_owner_model',
      'open_dialogue',
      'prepare_dialogue_context',
      'append_dialogue_turn',
      'get_dialogue',
      'commit_dialogue',
      'prepare_aether_context',
      'commit_aether',
    ],
  },
]

export const TOTAL_TOOL_COUNT = TOOL_CATEGORIES.reduce((sum, cat) => sum + cat.tools.length, 0)
