// GENERATED by apps/web/scripts/changelog-sync.mjs from /CHANGELOG.md. Do not edit by hand:
// edit the markdown, then run `npm run changelog:sync --workspace=apps/web`.
// In-app version shown in the Changelog modal header. package.json "version" is intentionally unused.

export const APP_VERSION = '0.49.0'
